/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */
/**
 * default freqency 2097kHz
 */

#include <stdint.h>

#include "main.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif


static inline void PWR_init();
static inline void GPIO_init();
static inline void UART_init();
static inline void DMA_init();



int main(void)
{
	uint8_t send_data[] = {'H', 'e', 'l', 'l', 'o', '\n', '\r'};

	PWR_init();
	GPIO_init();
	UART_init();
	DMA_init();

	/**
	 * DMA set
	 */
	DMA_set(DMA_CH_USART2_TX, (void*)&USART2->TDR, (void*)send_data);


	while(true){
		DMA_start(DMA_CH_USART2_TX, SizeByte, SizeByte, ToPeripheral, sizeof(send_data), false, false);
		GPIOA->ODR ^= (0b1 << 5);

		for(uint32_t i = 0 ;i < 1e5; ++i);
	}
}




void PWR_init(){
	RCC->APB1ENR |= RCC_APB1ENR_PWREN;
}
void GPIO_init(){
	/* A2 ->	UART2_TX
	 * A3 ->	UART2_RX
	 * A5 ->	LD2[output]
	 * A13 ->	SWDIO
	 * A14 ->	SWCLK
	 * C13 ->	B1[input]
	 */
	RCC->IOPENR |= RCC_IOPENR_GPIOAEN | RCC_IOPENR_GPIOCEN;

	//Reset A4,
	GPIOA->MODER =
			((GPIO_MODER_AF << GPIO_MODER_MODE2_Pos) | ~GPIO_MODER_MODE2_Msk) &
			((GPIO_MODER_AF << GPIO_MODER_MODE3_Pos) | ~GPIO_MODER_MODE3_Msk) &
			((GPIO_MODER_OUT << GPIO_MODER_MODE5_Pos) | ~GPIO_MODER_MODE5_Msk) &
			((GPIO_MODER_AF << GPIO_MODER_MODE13_Pos) | ~GPIO_MODER_MODE13_Msk) &
			((GPIO_MODER_AF << GPIO_MODER_MODE14_Pos) | ~GPIO_MODER_MODE14_Msk);
	GPIOC->MODER =
			(GPIO_MODER_IN << GPIO_MODER_MODE13_Pos) | ~GPIO_MODER_MODE13_Msk;

	GPIOA->PUPDR =
			(GPIO_PUPDR_PU << GPIO_PUPDR_PUPD13_Pos);

	GPIOA->AFR[0] =
			(0x4 << GPIO_AFRL_AFSEL2_Pos) |
			(0x4 << GPIO_AFRL_AFSEL3_Pos);
	GPIOA->AFR[1] =
			(0x0 << GPIO_AFRH_AFSEL13_Pos) |
			(0x0 << GPIO_AFRH_AFSEL14_Pos);
}
void DMA_init(){
    RCC->AHBENR |= RCC_AHBENR_DMAEN;
    DMA1_CSELR->CSELR |=  (0x4 << DMA_CSELR_C7S_Pos);
}
void UART_init(){
    /**
    * UART2 ->  9600bps
    * TX -> DMA1_CH7
    */

    RCC->APB1ENR |= RCC_APB1ENR_USART2EN;
    USART2->BRR = FREQENCY_DEF / 9600;

    /**
    * 8bit
    * parity none
    * stop1
    * over16
    * interrupt all disable
    * DMA Tx enable
    */
    USART2->CR1 |=
            USART_CR1_TE |
            USART_CR1_UE;
    //USART2->CR2;  //default
    USART2->CR3 |=
            USART_CR3_DMAT;
}
